# Another Kolor
## A custom theme for Sublime Text 2/3

In my development environment, I like to use the Dark version of a theme for code editing and the Light version of a theme for:

* Plain Text files (`.txt`)
* Markdown (`.mmd`, `.markdown`, `.md`)

This is a sample [markdown](https://daringfireball.net/projects/markdown/) document to demonstrate _how this theme works_.

Let’s look at code coloring for block quotes:

> Computer programming is an art, because it applies accumulated knowledge to the world, because it requires skill and ingenuity, and especially because it produced objects of beauty. A programmer who subconsciously views himself as an artist will enjoy what he does and will do it better.
> - Donald Knuth

And code samples:

```
    while(!successful)
    {
        tryAgain();
        if(dead)
            break;
    }
```

And more text.
